spring.application.name=core
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/data
spring.datasource.username=postgres
spring.datasource.password=25812581
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
meetyourmatch.client-id=53456162
minio.endpoint=http://localhost:9000
minio.access_key=Q3AM3UQ867SPQQA43P2F
minio.secret_key=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
#logging.level.org.springframework.security=TRACE